
theme = "monokai_pro"

[editor]
auto-format = false

[editor.whitespace]
render = "all"

[editor.file-picker]
hidden = false

[editor.cursor-shape]
insert = "bar"

[editor.indent-guides]
render = true
character = "⸽"
