add_newline = false

[directory]
home_symbol = ""

[java]
symbol = "  "
style= "red"

[git_branch]
symbol = " "

[package]
symbol= " "
style = "bold #FC9867"

[kubernetes]
disabled = false
format = "[$symbol$context](blue) "

[kubernetes.context_aliases]
'.*crc.*' = 'crc'
'.*openshiftapps.*' = 'sandbox'
'.*minikube.*' = 'minikube'

