add_newline = false

[directory]
home_symbol = ""

[java]
symbol = "  "
style= "red"

[git_branch]
symbol = " "

[package]
symbol= " "
style = "bold #FC9867"

[kubernetes]
disabled = false
format = "[⛵ $cluster/$user](blue) "

[kubernetes.user_aliases]
'developer/.*' = 'developer'
'kubeadmin/.*' = 'kubeadmin'

